#project information
site_name: Rebilly JS Token Library
site_description: Official Rebilly JS Token Documentation

#theme
theme:
  name: 'material'
  favicon: 'images/favicon.ico'

extra_css:
  - 'styles/extra.css'

extra:
  palette:
    primary: 'indigo'
    accent: 'deep purple'

#repo information
repo_name: 'Rebilly JS Token'
repo_url: 'https://github.com/Rebilly/rebilly-js-token'

# Copyright
copyright: 'Copyright &copy; 2017 Rebilly Inc.'

#extensions
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
       permalink: True
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.betterem:
       smart_enable: all
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.snippets:
        base_path: docs
  #  - pymdownx.smartsymbols

#page tree
nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Defining a Token: token-fields.md
  - Methods: methods.md
  - Generating a publishable API key: generating-api-key.md
  - Validation Tools: validation-tools.md
  - Common Errors: common-errors.md
  - License: license.md

